package com.nathaniel.carryapp.navigation

object Routes {
    const val INITIAL = "initial"
    const val DASHBOARD = "dashboard"
    const val ORDERS = "orders"
    const val SHOPPING = "shopping"
    const val ALERTS = "alerts"
    const val BROWSE = "browse"
    const val DELIVERY = "delivery"
    const val PICKUP = "pickup"
    const val SIGN_UP = "sign_up"
    const val SIGN_IN = "sign_in"
    const val DISPLAY_PROFILE = "display_profile"
    const val UPDATE_PROFILE = "update_profile"
    const val CHANGE_PASSWORD = "change_password"
    const val MEMBERSHIP = "membership"
    const val SUBSCRIPTION = "subscription"
    const val BADGE_DETAILS = "badge_details"
    const val VOUCHER = "voucher"
    const val SELECT_ORDER = "select_order"

    const val FORGOT_PASSWORD = "forgot_password"
    const val OTP = "otp"
    const val AGREEMENT_TERMS_PRIVACY = "agreement_terms_privacy"
    const val CATEGORIES = "categories"
    const val REORDER = "reorder"
    const val ACCOUNT = "account"
    const val PRODUCT_DETAIL = "product_detail"
    const val DELIVERY_AREA = "delivery_area"
    const val DELIVERY_ADDRESS = "delivery_address"
    const val LOCATION_CONFIRMATION_SCREEN = "location_confirmation_screen"
    const val CUSTOMER_DETAIL = "customer_detail"
    const val CASH_IN = "cash_in"
    const val CASH_IN_SUCCESS = "cash_in_success"
    const val CASH_IN_FAILED = "cash_in_failed"
    const val CART = "my_cart"
}